### ISSUE TITLE
Whitespaces are omitted from strings

### ISSUE THREAD

**Issue by AhmedHeshamSaad** [wvannoordt/PTL#1]
I coupled the PTL library with my Fortran code. Everything is working fine except whitespaces are omitted in strings.

For example:
`make forttest`
turns "helloworld" when changing the input to "hello world"

**Comment by wvannoordt** [comment]
Thanks for pointing this out, I will see if I can address this over the weekend!

**Comment by wvannoordt** [comment]
I have just addressed this issue on the master branch. If you have a string value with a space in it, can you try enclosing that string value with single quote marks now?

E.g.:
`variable = hello world`
should now be
`variable = 'hello world'`

**Comment by AhmedHeshamSaad** [comment]
Thank You!
I pulled it and it works on my end.
