### ISSUE TITLE
Program received signal SIGABRT, when parseing undefined REAL in the input script.

### ISSUE THREAD

**Issue by AhmedHeshamSaad** [wvannoordt/PTL#3]
When parsing a REAL value that is missing in the input script, it throws a PTLException and my Fortran program terminates giving the following error.

```
terminate called after throwing an instance of 'PTL::PTLException'
  what():  
---------------------------------------
PTLException thrown.
Message:
Cannot parse "" as double!
File: /home/ahmed/cfd_mr_stagnation/PTL/src/QueryResult.cpp
Line: 40
---------------------------------------

Program received signal SIGABRT: Process abort signal.
..........
```

The property name is not shown in the double quote in `Cannot parse "" as double!`. Which makes it difficult for the end-user to trace what is missing in the input script.

In the case of String, the PTL library returns an empty string, which I can handle inside my Fortran program, and throws an error with some instruction to the end-user. But in the REAL case, I can not handle such a mistake since PTL terminates and returns nothing.

Is there a way to handle that? 

Appreciate your help!

**Comment by wvannoordt** [comment]
I'll take a look over the weekend!

**Comment by wvannoordt** [comment]
Got around to fixing this, please see the changes in the fortran example.

**Comment by wvannoordt** [comment]
Also note that a couple of changes were made to the build system for fortran so let me know if that is causing issues.

**Comment by AhmedHeshamSaad** [comment]
I am sorry It took me a while to reply.
Yes, I tested it, and it works great.
Thank you!
